### ISSUE TITLE
Focus is not moving the out of the jExcel grid

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#1008]
Thank you very much Paul on pressing tab key focus is going to the first cell. Once the focus reaches to the last cell, focus is not moving out of the jExcel grid. 
Once the focus reaches to last cell on pressing the tab key please move the focus out of the jExcel grid.

_Originally posted by @Ilayaraja-n in https://github.com/paulhodel/jexcel/issues/891#issuecomment-640584308_

**Comment by Ilayaraja-n** [comment]
Hi,
Please check the attached screenshot and files, contains fix for this issue. I could not able to check-in or create pull request, hence requesting you to merge this changes for fixing this issue.

Code changes screenshot:
![Focus_Not_Moving_Out_Of_The_Grid-Fix](https://user-images.githubusercontent.com/46338652/142859925-b861a6a1-96a7-45d9-b4e1-0654059d7059.png)

Code Changes:

	} else if (e.which == 9) {
		// Tab
		var tempSelectedCell = jexcel.current.selectedCell.toString();
		if (e.shiftKey) {
			jexcel.current.left();
		} else {
			if (jexcel.current.options.allowInsertColumn == true) {
				if (jexcel.current.options.allowManualInsertColumn == true) {
					if (jexcel.current.selectedCell[0] == jexcel.current.options.data[0].length - 1) {
						// New record in case selectedCell in the last column
						jexcel.current.insertColumn();
					}
				}
			}
    
			jexcel.current.right();
		}
		if(tempSelectedCell != jexcel.current.selectedCell.toString()){ 
			e.preventDefault();
		}else{
			jexcel.current.resetSelection();
		}
	} else {
		if ((e.ctrlKey || e.metaKey) && ! e.shiftKey) {
			if (e.which == 65) {
				// Ctrl + A

**Comment by hodeware** [comment]
Thanks for the suggestion.

But I don't believe that feature should go in the core distribution. Firstly that will impact everyone used with the current behavior, and secondly, different users would have different expectations in re to that.

For example:

1) On the last column tab means expand the grid and create a new column automaticaly;

2) On the last column tab means go to the first column in the row below.

3) On the last column tab means lose the focus if the allowInsertColumn is false.


So, because those and other expectations you should implement that using one of the available events, such as onselection or with some sort of new initial settings, so current users are not disrupt by your changes in the core.

Another point, if you implement that on the core, but not official distribution. When a new release is available, you will need to keep merging your changes or stuck on the version you have customize. So, that is not a good practice.

**Comment by Ilayaraja-n** [comment]
Thank you so much Paul. Focus is not coming out of the grid once the focus is inside the grid. We need to use mouse click explicitly to come out of the gird.

The changes I have suggested will not affect the current behavior you have mentioned, and this will happen only in the scenario, where the focus is in the last cell of the row/grid and insertColumn flag is false.

Please find inline comments as below
1.	On the last column tab means expand the grid and create a new column automatically;
        Code changes will not have any impact
2.	On the last column tab means go to the first column in the row below.
        Currently focus stays on the last column only and it does not move to row below
3.	On the last column tab means lose the focus if the allowInsertColumn is false.
        Currently focus stays on the last column only and the focus does not move out the grid. The code changes suggested will move the focus out of the grid.

Please suggest.
