### ISSUE TITLE
Pasting from excel issue

### ISSUE THREAD

**Issue by dermotcarey** [jspreadsheet/ce#101]
Not sure if there is anything that can be done about this. 
If I paste data from Excel into a table. It will paste not only the intended Cell(s) but also also an extra row below. So if there is any data in that row it will be overwritten with blanks. 
I think this is because when you copy from Excel it adds and extra line feed in the clipboard. 
Is there anything that can be done about this?

**Comment by pphod** [comment]
The problem is all software use \t to detect the data to be pasted in different cells. Even Excel will have this problem. For example, if you type on your notepad (a \t  b \t  c) and paste on excel you going to see a, b, c in three different columns. But, if you want to copy a, c only them b will be erased.
