### ISSUE TITLE
Resizing large table is slow.

### ISSUE THREAD

**Issue by earboxer** [jspreadsheet/ce#103]
Resizing a column on a medium sized (30x30) spreadsheet often lags, and resizing columns on larger spreadsheets (100x50) is almost unusable.

**Comment by pphod** [comment]
Could you open an example you are working in the jsfiddle?

**Comment by pphod** [comment]
I have created a simple example and it is working fine with 100x50 for example.
https://jsfiddle.net/paulhodel/du585ux2/

There should be another reasons for the table is so slow for this quantity, since it is not big table. I know that really large quantities can make the browser slow, but I mean 1000+, 10000+ rows. In that particular case we are thinking to implement a lazy loading.
