### ISSUE TITLE
Editable Dropdown

### ISSUE THREAD

**Issue by kAvItHa-cL** [jspreadsheet/ce#1067]
Hi, is there any possibility to have Editable dropdown, in which copy paste, selecting option from existing one or adding new options are supported

**Comment by flywalt** [comment]
no orginal method is available currently, but there is a solution based on jsuite which is also built by Paul
however i forgot in which issue it is mentioned - -b

**Comment by pphod** [comment]
You can add options programatically. There is a conditional filter which you can return new options based on a script.
https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete

You can also add options straight in the source property in the column
table.options.column[colNumber].source

jSuites in the most recent version can handle new options, but you should implement the correct events in order to update the source with the new options added. This will be better supported in a new future when we release jExcel CE v5.
