### ISSUE TITLE
Popup tooltips on Headers 

### ISSUE THREAD

**Issue by mopena** [jspreadsheet/ce#1088]
Is there a way to hide the tool tips that pop-up showing in the column headers. It is basically popping up the same text column title? Thanks

**Comment by pphod** [comment]
Sorry, there is no way to hide it. We use that as a internal control.

**Comment by phuze** [comment]
It's my opinion that these tooltips don't make much sense from a UX perspective. Duplicating the header in the form of a tooltip does not offer value to the user and doesn't respect application UI. Moreover, they are not uniquely name-spaced and so the classes can easily conflict with existing styles. They are also positioned in a manner that doesn't seem to respect relative fluidity. In my case, I just end up with some text matching the header, appearing in a random spot within my view. I'm having a difficult time understanding what internal control requires you to render a tooltip in the DOM?

@mopena 
You certainly can hide these. It's just a div element, which you can target in several ways. The element being created by the jExcel library looks like this -- note that the `id` is dynamically generated on each hover event.

```
<div role="tooltip" id="ui-id-12" class="ui-tooltip ui-corner-all ui-widget-shadow ui-widget ui-widget-content">
    <div class="ui-tooltip-content">
        ...
    </div>
</div>
```

So you can simply hide it using some CSS. Your mileage may vary depending on your specific application styles. For example:

```
div[role="tooltip"][class*="ui-tooltip"] {
    display: none !important;
}
```

In the event you can't match on class, perhaps because it conflicts with an existing application style, then you can also try matching on the `id`, by looking for the beginning part:

```
div[role="tooltip"][id^="ui-id"] {
    display: none !important;
}
```

**Comment by 0Chan-smc** [comment]
@phuze I agree with you. But your solution seems to be not working at v4.10.1 😢.

**Comment by 0Chan-smc** [comment]
Oh, I've came up with an idea.
I cleared the title attribute of thead > td to an empty string.
```
const td = document.querySelectorAll('div.jexcel_content > table > thead > tr > td');
td[0].title = '';
```
I hope this helps someone.
