### ISSUE TITLE
On selection is even working while clicking on scroll bar or context menu

### ISSUE THREAD

**Issue by VivekSharmaTechM** [jspreadsheet/ce#1160]
Hi,

I am opening a popup window onselection event. so whenever someone click on cell popup comes up. but it is also working 
on selection of scroll bar or using context menu to add row. while u click on the scroll bar it automatially select first cell and open the popup. can you suggest some other event or some work around fr that.

**Comment by pphod** [comment]
This is because you are losing the focus when the element is outside the jexcel container. There should be an alternative for that on future versions, but for now, you should add your popup DOM element inside the jexcel_container.

On the Pro distribution, you can have a DOM element part of jexcel (keep the focus), adding a CSS class: jexcel_object on the external element.
