### ISSUE TITLE
Background Color Lost On Scrolling Fixed Columns

### ISSUE THREAD

**Issue by auto-mate** [jspreadsheet/ce#1338]
Great library, just started using this week, I have colored the background of a fixed column and it returns to white when scrolling.
I've added a fiddle [here](https://jsfiddle.net/ojy37mqz/) to demonstrate.

**Comment by Alex-Monahan** [comment]
All you need to do is edit the css of .jexcel_freezed in JExcel.css!
Removing the background-color should do the trick.

**Comment by hodeware** [comment]
@auto-mate it is important to keep the background for the frozen cells. That is because, if no background color is defined the stuck cells would be transparent showing the content of the cells behind bringing a bad experience. Said that you can overwrite the colors using CSS or using !important to overwrite the default white ones.
