### ISSUE TITLE
How can i get cell address like A1, A2, A3,... Thank you so much 💯 

### ISSUE THREAD

**Issue by hieuhgt1** [jspreadsheet/ce#1405]

**Comment by GBonnaire** [comment]
?? Can you explain more…

**Comment by hieuhgt1** [comment]
> ?? Can you explain more…

I can get cell address by **getColumnNameFromId** now. But another issue is that when i copy a cell and paste it and it copy also the style of it but i want it just copy text and not style. May I do that because i need to validate text input by each column. Thank u so much

**Comment by hieuhgt1** [comment]
For more detail, it is paste the value only not paste the format

**Comment by GBonnaire** [comment]
If you use jSpreadsheet pro, you can use this plugin : https://jspreadsheet.com/plugins/advanced-copy-and-paste

Otherwise, i don't know if on version CE, when you paste, you paste style+data, because on code, i see only data. But, try to use event `onbeforepaste`. 

`onbeforepaste: function(el, data, x, y) {...}` on this function you can return value pasted and controlled
