### ISSUE TITLE
Pasting quotation marks fails

### ISSUE THREAD

**Issue by b747fp** [jspreadsheet/ce#176]
Pasting in text that contains " quotation marks fails, it cuts off at the "  and does not finish pasting the rest... How can this be avoided?

**Comment by pphod** [comment]
Unclose double-quote will be consider an error. Even in excel if you have a unclose double quotes and you copy and paste on notepad, you will see another double quote included automatically.

**Comment by b747fp** [comment]
Well i need to disable the excel-like feature on this then because these people are copying and pasting from Excel with " used to delineate inches, and it's not pasting into this jexcel.  So clearly since they're copying from Excel you're wrong stating that it doesnt work in Excel... How do i work around this so they can paste their text into the cells on jExcel?

**Comment by b747fp** [comment]
i notice if i change it to & quot;  and then paste it in, it goes in fine... can i add a filter to the paste action?

**Comment by pphod** [comment]
New events have been included and are available in the master repo for download. 

onpaste
onbeforepaste (you can use that to filter your input string before the parser).

The copy method from jExcel has been updated to escape a single double quote. This is the same behaviour from Excel and it will help the compatibility coping data from jExcel to Excel.

I don't understand when you copy from excel and paste is not working for you, since excel is escaping by always changing " to "".

**Comment by b747fp** [comment]
yea i didnt find it, a customer i used this for noticed it when they were doing their data entry. thanks for fixing quickly.  the onbeforepaste worked perfectly using  .replace(/"/g, '& quot;')

**Comment by pphod** [comment]
Bear in mind " is a control character from CSV, doing that you can cause unexpected results.

**Comment by b747fp** [comment]
we are not using this for CSV, we are using it for them to paste their massive data in excel into a more organized mysql table via ajax onchange commands
