### ISSUE TITLE
Conflict on Formula of Dynamic Loaded Content

### ISSUE THREAD

**Issue by droymanz** [jspreadsheet/ce#178]
Can you help me with this again man?

I have 2 tables. The 1st table was loaded already and the 2nd table has to be refreshed by loading it again dynamically because some of the values on the 2nd table came from the first table. 
This is the fiddle that I made [https://jsfiddle.net/rymawtg4/](https://jsfiddle.net/rymawtg4/) though this is not exactly what I really want but it has the same error as my app.

Thanks in advance.

**Comment by paulhodel** [comment]
Yes I can see the behaviour... I am need to create a patch for that. I will get back to you as soon as the new fix is ready...

**Comment by pphod** [comment]
When jExcel render a formula the own spreadsheet should be selected. The problem is, if your method load and render a second spreadsheet while the first one is selected (focus). This will make the values of the columns from the first spreadsheet applied to the second. But, there is a workaround for your case. Before render the second spreadsheet you should change the focus. I have updated your jsfiddle included a line before your render:

$.fn.jexcel.current = 'my1';

See in action:
https://jsfiddle.net/rymawtg4/3/

**Comment by droymanz** [comment]
Thanks a lot man!
