### ISSUE TITLE
Retrieve calculated values

### ISSUE THREAD

**Issue by groliffe** [jspreadsheet/ce#225]
At the moment, if any of your cells contain a formula, using 'getData' or 'download' returns the formula expression in that cell.

Is there any way to retrieve the whole table with the current calculated values instead?

Cheers

Lance

**Comment by pphod** [comment]
You can get the value from one cell, but not the entire table since it would block the portability of the data. To get a individual cell, the easiest way:

$('yourtable').find('#0-0').text(); // for Colum A1
$('yourtable').find('#1-0').text(); // for Colum B1
$('yourtable').find('#2-0').text(); // for Colum C1
$('yourtable').find('#0-1').text(); // for Colum A2
$('yourtable').find('#0-2').text(); // for Colum A3

etc...

I am going to leave the issue open to discuss a possibility to incorporate the full export with the values only.

**Comment by dansteingart** [comment]
There's a bug/inconsistent behavior when one applies formatting to the table (e.g. currency formatting). When you run `getData` on a currency formatted table, it returns the values, not the expressions. 

The expressions still work, but if one wants to save state this can cause problem if you want to preserve formulae to edit later. A work around is to keep a copy of the expressions later, but for consistency it seems that `getData` should return the pre-formatted cells.

**Comment by pphod** [comment]
I am not sure if I understood your last comments. Could you test that on the new version v2.0.0 if you can explain your problem with examples will be great.
