### ISSUE TITLE
Copy/paste from Excel ... dropdown lists

### ISSUE THREAD

**Issue by argentinteractive** [jspreadsheet/ce#354]
Hi,

I have a table set up with 6 columns:
text, text, dropdown, text, dropdown, text

For arguments sake my dropdown list has three options built via external json from my database. This list needs to be dynamic and will change frequently.
[{"name": "Toast", "id": "1"},
{"name": "Eggs", "id": "2"},
{"name": "Bacon", "id": "3"}]

Dropdown data loads okay, however when I copy data from Excel the dropdown cells are not set, only the text. I worked out this seems to be because jexcel is expecting the "id". If I change my Excel data to be "1" instead of "Toast" it sets the dropdown value correctly.

Is there a way to set up the jexcel table so I can copy/paste the name value for my dropdown to set it or am I stuck?

Thanks

**Comment by jeremycook** [comment]
I'm new to jexcel and am only offering a suggestion that is based on assumptions that may be totally wrong.

The docs mention the "onbeforechange" event. It seems like you could intercept that event, determine if you are pasting into a dropdown list that has an id-name-pair, and then do a lookup based on the incoming value and map it to its `id` if that `name` is found...if not found then leave the value alone.

I debated doing something like that but decided to keep things simple and just have a dropdown of strings instead of a dropdown of {id: "...", name: "..."} objects so that copy-pasting just works. I then deal with mapping the name to an id server side. It would be nice if jexcel automatically did something like what I described.

**Comment by pphod** [comment]
That is implemented on the Pro distribution and should be brought to CE eventually.

**Comment by tsh356** [comment]
> That is implemented on the Pro distribution and should be brought to CE eventually.

How does copy-paste in dropdowns work in Pro? I'm not seeing it in the docs and with my current settings, it still copies only text.

**Comment by pphod** [comment]
Hi Taylor,
When you copy from excel or any other software a text and paste on jexcel dropdown cell, jexcel should recognize codes or matching text to the options available in the dropdown.

For example:

1) Go to this page:
https://jexcel.net/v7/examples/dropdown-and-autocomplete

2) Open your notepad and type "United states" copy the text and paste on Jexcel first column (any row).

3) Note that if you do the same and copy "US" and paste on the same row, the result should be the same, because I have defined the dropdown as:

source: [{ id:'US', name:'United States'}, etc...]

This is the native behavior from v7+, on previous versions that dropdown was accepting only codes.

**Comment by tsh356** [comment]
Perfect thanks!

I was running 7.0. Upgrade to the latest and it works great.

**Comment by jaky1227** [comment]
Does this has been fixed in CE?
