### ISSUE TITLE
cannot select .jexcel_label in 2.1.0

### ISSUE THREAD

**Issue by dexterouschen** [jspreadsheet/ce#372]
if ($(e.target).parents('.jexcel-content').length) {
  var target = (e.target.tagName == 'TD') ? e.target : $(e.target).parents('td');
    **if ($(target).length && $(target).prop('id')) {**
      // Update row label selection
      if ($(e.target).is('.jexcel_label')) {
      ...

the marked line is preventing a row from being selected, `.jexcel_label`'s don't have ids.

**Comment by TheNeverK** [comment]
I'm facing the same problem. Just like @dexterouschen said, check on the 742 line disables row selection, because cells with `.jexcel_label` don't have ids. Is this condition necesary? If so, the problem can be ommited by simply adding any id on lines 1526: https://github.com/paulhodel/jexcel/blob/80f60bd12d024d850608cb859ed2d6e1232fc873/dist/js/jquery.jexcel.js#L1526
and 3257: https://github.com/paulhodel/jexcel/blob/80f60bd12d024d850608cb859ed2d6e1232fc873/dist/js/jquery.jexcel.js#L3257
I'm proposing something like `rh-XX` where `XX` is the line number, so the code has to be changed like this:
1526: `$(tr).append('<td class="jexcel_label" id="rh-'+(j+1)+'">' + parseInt(j + 1) + '</td>');`
3257: `$(tr).append('<td class="jexcel_label" id="rh-' + rowNumber + '"></td>');`
What do you think?

**Comment by pphod** [comment]
/**
     * Show index column
     */
    obj.showIndex = function() {
        obj.colgroupContainer.children[0].width = 40;
    }

    /**
     * Hide index column
     */
    obj.hideIndex = function() {
        obj.colgroupContainer.children[0].width = 0;
    }
