### ISSUE TITLE
jExcel v3 formulas not show correctly after sort or paste

### ISSUE THREAD

**Issue by lyuyifei** [jspreadsheet/ce#438]
https://bossanova.uk/jexcel/v3/examples/sorting 
when you change column B4 to '=SUM(B1:B3)' then click any header to sort the table, it looks fine. However if you click the column B4, the formulas changed to '=SUM(B2:B3)'.

**Comment by pphod** [comment]
I am going to add a note in the documentation. If you want to formulas my suggestion is to desactivate the sorting. Imagine this:

=B1*C1
=B2*C2
=B3*C3
=SUM(D1:D3)


If I sort that, and let's suppose the four became the second.

=B1*C1
=SUM(D1:D3)
=B3*C3
=B4*C4

This will generate error since it will be an auto reference and you can do that, otherwise will generate unexpected behaviors, loops, etc.

The solution for that is create a new layer in the table (such as the footer), where we can have totalizers and those rows won't be included in the body of the content.

Sorry, but this is a limitation... and there is no much I can do.
