### ISSUE TITLE
jexcel.setData possibly uses wrong value for number of columns

### ISSUE THREAD

**Issue by lucBoillat** [jspreadsheet/ce#596]
https://github.com/paulhodel/jexcel/blob/e8054ac3e5df3a7b466f525531688a670fa20e49/dist/jexcel.js#L586

Is there a reason why the size_i value is determined from the current grid size and not from the data that was passed to the setData function? obj.options.data[0].length would make more sense to me. If my table is of size 1x1 and i pass a 20x20 array into setData, the resulting grid is 1x20.

**Comment by pphod** [comment]
obj.options.columns.length should be equal to obj.options.data[0].length. But, not always because the second relies on the user input, the first relies on the configurations of the table and there are several adjustments and protections to make sure all columns have the minimum definition for the correct table behavior.

For example:
[
  [0,1,2],
  [01,2,3,4,5,6,7],
  [01,2,3,4,5,6,7],
  [01,2,3,4,5,6,7],
  [01,2,3,4,5,6,7],
]

In the example above, If I rely on the data[0].length your table will have 3 or 8 columns? because it relies on the columns.length the table understand the correct size.
