### ISSUE TITLE
Performance issue during rendering for 3200row X 110col

### ISSUE THREAD

**Issue by bilencekic** [jspreadsheet/ce#700]
I have a performance issue during rendering for 3200 rows and 110 columns. I am using lazy load but jexcel trying to append all html content at once and taking around 6-10 seconds to render.
For below code, if i limit to append 100 elements only , it renders very fast. is there a way to make it working like lazyLoading style ? It can append during scrolling, will it be slow in this case ?
![Error](https://i.imgur.com/uDWUKY6.png)

**Comment by pphod** [comment]
I am happy to discuss that on Skype.

My skype account: paul.hodel

**Comment by mansoor88** [comment]
I have one year record. Which have 365 days as rows and it have formulation in some cells. It slow down the loading of grid. Web service respond in quick time but page grid load takes about 15 second time to load. If i switch to month. Than grid loads 31st days record quickly. What can be the solution?

**Comment by pphod** [comment]
Are you using the most recent version?

**Comment by mansoor88** [comment]
I am using 3.6.2. is it the latest one?

**Comment by mansoor88** [comment]
Ok I update it from 3.6.2 > 3.6.3. I changed the jexcel dist files css and js with updated one and replace the package.json as well. Still the issue exist.

**Comment by mansoor88** [comment]
Alright i have checked one more thing. If i load without calculation it loads very quickly. The one with calculation takes time to load for 365 rows. Thanks

**Comment by pphod** [comment]
Mansoor, can you create a jsfiddle with your example? I pretty sure there is room from improvement.

**Comment by mansoor88** [comment]
> 
> 
> Mansoor, can you create a jsfiddle with your example? I pretty sure there is room from improvement.

Hi. Thanks for response. Please check the jsfiddle link
https://jsfiddle.net/yz57ktmf/

**Comment by pphod** [comment]
Mansoor.

I have checked your example. I debug to see if there is anything, in this case, to make it fast. But, unfortunately, your spreadsheet creates a chain of 600+ formulas to be executed if you change the second row. So, basically, JS is slow enough to impact the performance of the task. I have a check for duplications or optimizations, but jExcel is only waiting for all formulas to be executed, and in this case, should wait for the result of one formula to trigger the next since it is a chain of executions, therefore there is no much I can do in jExcel side.

Sorry, but this is a browser limitation. You should avoid cascade formulas.

Best regards,
