### ISSUE TITLE
What is extra benefits in purchased version ? 

### ISSUE THREAD

**Issue by mayankvadia** [jspreadsheet/ce#789]
What is extra benefits in purchased version ?

**Comment by pphod** [comment]
Support, Performance, A exclusive extra features, new constant updates/improvements.

**Comment by mayankvadia** [comment]
Thanks @paulhodel ,

May I known what is extra features in purchased version ?

**Comment by pphod** [comment]
Jexcel 4.0.1
Freeze columns
Multiple columns resize
New smart key navigation
New smart merge cell methods
Support for large tables, only loads what is necessary when using lazyloading or pagination
Faster formula engine
New native formula methods
Superevent: centralized event handler method
Easier backend integration

Plus better way to handler server side updates.

**Comment by pphod** [comment]
You can find more examples here:
https://jexcel.net/v4/cases/project-management
http://jexcel.net/v4/cases/data-persistance

**Comment by tsh356** [comment]
Is v4 lazy loading better/faster than v3 lazy loading?

**Comment by pphod** [comment]
Yes, the engine of formulas and loading is much better. In the lazyloading/pagination, the DOM element will be created as they needed. It is very easy to test, open the pagination example and paste 10K records on v3. The browser will freeze since there are a lot of DOM to be created. In v4 you can paste 100K records without no problem.
