### ISSUE TITLE
The right way of change a big data

### ISSUE THREAD

**Issue by VictorCandido** [jspreadsheet/ce#834]
Hi @paulhodel ,
I have a spreadsheet of more than 1100 rows and I need to change the value of an entire column, for example, but this column is a paramter for another column with a formula. I'm using "setColumnData" or "setValue" or even the "setRowData", but, because of the formulas and the quantity of data, those functions become very slow. What is the rigth way to do that?

**Comment by pphod** [comment]
Hi Victor, this is hard to say without looking at your code. I can try to take a look if you create a jsfiddle with some dummy data and give you better advice.

It all depends really on the formula chain. Basically how many operations the spreadsheet needs to perform. One thing can really help is not using onchange, but onafterchanges.

If the problem is actually the amount of DOM elements, you should consider going to jExcel Pro.

https://jexcel.net/v4

You will have great technical support from only 4.90 pounds/month.

Regards,

**Comment by VictorCandido** [comment]
@paulhodel 
Is there any way of, at least disable the formulas processing and after, update all the formulas? I'm thinking of a button that will toggle this action according the user's will...

**Comment by pphod** [comment]
Hi Victor, I am happy to give you a closer technical support to make sure you can achieve your goals. Call you to add me on your skype skype: paul.hodel

**Comment by honey-system** [comment]
> Hi @paulhodel ,
> I have a spreadsheet of more than 1100 rows and I need to change the value of an entire column, for example, but this column is a paramter for another column with a formula. I'm using "setColumnData" or "setValue" or even the "setRowData", but, because of the formulas and the quantity of data, those functions become very slow. What is the rigth way to do that?

Maybe my answer can help you:
https://github.com/paulhodel/jexcel/issues/846

**Comment by mustantriveni** [comment]
Hi
If the problem is actually the amount of DOM elements, you should consider going to jExcel Pro.

https://jexcel.net/v4

You will have great technical support from only 4.90 pounds/month.

Regarding this How much it cost in INR per month?
Thank You in Advance

**Comment by mustantriveni** [comment]
@paulhodel 
Hi
If the problem is actually the amount of DOM elements, you should consider going to jExcel Pro.

https://jexcel.net/v4

You will have great technical support from only 4.90 pounds/month.

Regarding this How much it cost in INR per month?
Thank You in Advance
